CREATE TABLE IF NOT EXISTS pon_c320(
    `OLT_IP` varchar(16) not null default "127.0.0.1",
    `OLT_NAME` varchar(255) not null default "localhost",
    `ONU` varchar(50) not null,
    `ONU_FULL_ID` varchar(255) not null unique,
    `ONU_NUMBER` integer not null,
    `ONU_ADMIN_STATE` varchar(20),
    `ONU_OMCC_STATE` varchar(20),
    `ONU_PHASE_STATE` varchar(20),
    `ONU_CHANNEL` varchar(20),
    `ONU_INTERFACE` varchar(50),
    `NAME` varchar(20),
    `TYPE` varchar(50),
    `STATE` varchar(50),
    `CONFIGURED_CHANNEL` varchar(50),
    `CURRENT_CHANNEL` varchar(50),
    `ADMIN_STATE` varchar(50),
    `PHASE_STATE` varchar(50),
    `CONFIG_STATE` varchar(50),
    `AUTHENTICATION_MODE`varchar(50),
    `SN_BIND` varchar(50),
    `SERIAL_NUMBER` varchar(50),
    `PASSWORD` varchar(50),
    `DESCRIPTION` varchar(255),
    `VPORT_MODE` varchar(50),
    `DBA_MODE` varchar(50),
    `ONU_STATUS` varchar(50),
    `OMCI_BW_PROFILE` varchar(50),
    `LINE_PROFILE` varchar(50),
    `SERVICE_PROFILE` varchar(50),
    `ONU_DISTANCE` varchar(50),
    `ONLINE_DURATION` varchar(50),
    `FEC` varchar(50),
    `FEC_ACTUAL_MODE` varchar(50),
    `PPS__TOD`  varchar(50),
    `AUTO_REPLACE`  varchar(50),
    `MULTICAST_ENCRYPTION`  varchar(50),
    `ACTIVE_SESSION_START_DATE`  varchar(50),
    `ACTIVE_SESSION_START_TIME`  varchar(50),
    `PREV_SESSION_REASON`  varchar(50),
    `PREV_SESSION_START_DATE`  varchar(50),
    `PREV_SESSION_START_TIME`  varchar(50),
    `PREV_SESSION_END_DATE`  varchar(50),
    `PREV_SESSION_END_TIME`  varchar(50),
    `TOTAL_MAC_ADDRESSES` integer default 0,
    `SIGNAL_LEVEL_UP_RX` float,
    `SIGNAL_LEVEL_UP_TX` float,
    `SIGNAL_LEVEL_UP_ATTENUATION` float,
    `SIGNAL_LEVEL_DOWN_RX` float,
    `SIGNAL_LEVEL_DOWN_TX` float,
    `SIGNAL_LEVEL_DOWN_ATTENUATION` float,
    `MACS` text
);